export const locators = {
    usernameField: '[data-test="username"]',
    passwordField: '[data-test="password"]',
    submitButton: '[data-test="login-button"]',
    productAddedToCartLocator: '[data-test="add-to-cart-test.allthethings()-t-shirt-(red)"]',
    cartIconLocator: '[data-test="shopping-cart-link"]',
    cartContentsContainerLocator: '[data-test="cart-contents-container"]',
    checkoutButtonLocator: '[data-test="checkout"]',
    firstNameField: '[data-test="firstName"]',
    lastNameField: '[data-test="lastName"]',
    postalCodeField: '[data-test="postalCode"]',
    continueButton: '[data-test="continue"]',
    finishButton: '[data-test="finish"]',
    checkCompleteContainer: '[data-test="checkout-complete-container"]',
    continuShoppingButton: '[data-test="continue-shopping"]',
    primaryHeader: '[data-test="primary-header"]',
    logoutSidebarLink: '[data-test="logout-sidebar-link"]',
};
